= Cilium Cluster Mesh FAQ

== Interaction of Network Policies and Cilium Cluster Mesh

Cilium Cluster Mesh treats namespaces with the same name on different clusters as the same namespace.
This facilitates the default cross-cluster load-balancing use case of Cluster Cluster Mesh with minimal network policy adjustments.

However, if you want to isolate namespaces with the same name on different clusters from each other, you must specify the local cluster via the `io.cilium.k8s.policy.cluster` label.
VSHN Managed OpenShift uses the cluster's Project Syn ID as the Cilium Cluster Mesh cluster name.

[NOTE]
=====
By default, the VSHN Managed OpenShift namespace isolation allows cross-cluster traffic between pods in namespaces with the same name on different clusters.
On request, we can enable cross-cluster isolation in the VSHN Managed OpenShift default network policies.
=====

The following example policy https://docs.cilium.io/en/latest/network/clustermesh/policy/#allowing-specific-communication-between-clusters[from the Cilium documentation] illustrates how to allow particular pods to communicate between two clusters:

[source,yaml]
----
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-cross-cluster"
spec:
  description: "Allow x-wing in cluster1 to contact rebel-base in cluster2"
  endpointSelector:
    matchLabels:
      name: x-wing
      io.cilium.k8s.policy.cluster: kind-cilium-mesh-1
  egress:
  - toEndpoints:
    - matchLabels:
        name: rebel-base-dev
        k8s:io.kubernetes.pod.namespace: dev
        io.cilium.k8s.policy.cluster: kind-cilium-mesh-2
----
